## 
## Note: this file's content was created using VNEI
## 
## compiled from mod version: 0.4.2
## 
groups:
  Consumable_DoOrDieMonsters:
    - CarnivorBait_DoD
    - Apple_DoD
    - Cherries_DoD
    - Banana_DoD
    - Walnuts_DoD
    - BlueMushroom_DoD
    - PurpleMushroom_DoD
  Material_DoOrDieMonsters:
    - InfusedGemstone_DoD
    - DeathKnightItem_DoD
    - ArcherItem_DoD
    - BerserkerItem_DoD
    - DruidItem_DoD
    - MageItem_DoD
    - MonkItem_DoD
    - NinjaItem_DoD
    - PaladinItem_DoD
    - RogueItem_DoD
    - ShamanItem_DoD
    - WarlockItem_DoD
    - BoarTusk_DoD
    - LargeFang_DoD
    - ShamansVessel_DoD
    - GreydwarfHeart_DoD
    - SkeletonBones_DoD
    - GreyPearl_DoD
    - FrozenBone_DoD
    - CharredBone_DoD
    - FrostlingCore_DoD
    - StormlingCore_DoD
    - VoidlingCore_DoD
    - ForestWolfPelt_DoD
    - DireWolfPelt_DoD
    - WaterGlobe_DoD
    - SpiderChitin_DoD
    - BlackDeerHide_DoD
    - OakWood_DoD
    - SteelBar_DoD
    - FrometalOre_DoD
    - FrometalBar_DoD
    - FelmetalOre_DoD
    - FelmetalBar_DoD
    - CrudeArmorKit_DoD
    - BasicArmorKit_DoD
    - GoodArmorKit_DoD
    - GreatArmorKit_DoD
    - SuperiorArmorKit_DoD
    - ExcellentArmorKit_DoD
    - ExceptionalArmorKit_DoD
    - ExtraordinaryArmorKit_DoD
    - CrudeWeaponKit_DoD
    - BasicWeaponKit_DoD
    - GoodWeaponKit_DoD
    - GreatWeaponKit_DoD
    - SuperiorWeaponKit_DoD
    - ExcellentWeaponKit_DoD
    - ExceptionalWeaponKit_DoD
    - ExtraordinaryWeaponKit_DoD
  Bow_DoOrDieMonsters:
    - Bow_FrozenBones_DoD
    - Bow_SkelR_DoD
    - Bow_SkelG_DoD
    - Bow_Charred_DoD
    - Bow_DeepNorth_DoD
    - Bow_Plains_DoD
    - Bow_Mountain_DoD
    - Bow_Swamp_DoD
    - Bow_BlackForest_DoD
  TwoHandedWeapon_DoOrDieMonsters:
    - MonkMace_DoD
    - BerserkerAxe_DoD
    - DruidSpear_DoD
    - NinjaSword_DoD
  OneHandedWeapon_DoOrDieMonsters:
    - ShamanWand_DoD
    - MageWand_DoD
    - WarlockWand_DoD
    - PaladinMace_DoD
    - RogueSword_DoD
    - DeathknightAxe_DoD
    - Mace_DeepNorth_DoD
    - Mace_Mistlands_DoD
    - Wand_Mountain_DoD
    - SwordFlametal1_DoD
    - SwordFlametal2_DoD
    - SwordFelmetal1_DoD
    - SwordFelmetal2_DoD
    - Stormblade_DoD
    - SwordFrometal2_DoD
    - SwordFrometal1_DoD
    - SwordFrometal3_DoD
    - SwordSpirit_DoD
    - Sword_AshLands_DoD
    - Sword_DeepNorth_DoD
    - Sword_Plains_DoD
    - Sword_Swamp_DoD
    - Sword_Meadows_DoD
  Shield_DoOrDieMonsters:
    - BrokenShieldBhygshan_DoD
    - BrokenShieldEikthyr_DoD
    - BrokenShieldRambore_DoD
    - BrokenShieldElder_DoD
    - BrokenShieldBitterstump_DoD
    - BrokenShieldBonemass_DoD
    - BrokenShieldModer_DoD
    - BrokenShieldFarkas_DoD
    - BrokenShieldSkir_DoD
    - BrokenShieldYagluth_DoD
    - ShieldYagluth_DoD
    - ShieldSkir_DoD
    - ShieldModer_DoD
    - ShieldBonemass_DoD
    - ShieldBitterstump_DoD
    - ShieldElder_DoD
    - ShieldRambore_DoD
  Trophie_DoOrDieMonsters:
    - TrophyCharredRemains_DoD
    - TrophyFrozenBones_DoD
    - TrophyGreatSurtling_DoD
    - TrophySkeletonG_DoD
    - TrophySkeletonR_DoD
    - TrophyFrostling_DoD
    - TrophyStormling_DoD
    - TrophyVoidling_DoD
    - TrophyOGolem_DoD
    - TrophyLGolem_DoD
    - TrophyIceGolem_DoD
    - TrophyVilefang_DoD
    - TrophyDireWolf_DoD
    - TrophyForestWolf_DoD
    - TrophyLivingLava_DoD
    - TrophyLivingWater_DoD
    - TrophyBlackDeer_DoD
    - TrophyIceDrake_DoD
    - TrophyFlameDrake_DoD
    - TrophyArcaneDrake_DoD
    - TrophyDarknessDrake_DoD
    - TrophyGoldDrake_DoD
    - TrophyPoisonDrake_DoD
    - TrophyDarkDrake_DoD
  ## extra groups, beyond the mod type groups
  Weaponkits_DoOrDieMonsters:
    - CrudeArmorKit_DoD
    - BasicArmorKit_DoD
    - GoodArmorKit_DoD
    - GreatArmorKit_DoD
    - SuperiorArmorKit_DoD
    - ExcellentArmorKit_DoD
    - ExceptionalArmorKit_DoD
    - ExtraordinaryArmorKit_DoD
    - CrudeWeaponKit_DoD
    - BasicWeaponKit_DoD
    - GoodWeaponKit_DoD
    - GreatWeaponKit_DoD
    - SuperiorWeaponKit_DoD
    - ExcellentWeaponKit_DoD
    - ExceptionalWeaponKit_DoD
    - ExtraordinaryWeaponKit_DoD
  Metal_DoOrDieMonsters:
    - SteelBar_DoD
    - FrometalBar_DoD
    - FelmetalBar_DoD
  Ore_DoOrDieMonsters:
    - FrometalOre_DoD
    - FelmetalOre_DoD
  Stackable_DoOrDieMonsters:
    - Material_DoOrDieMonsters
    - Trophie_DoOrDieMonsters
  Equipment_DoOrDieMonsters:
    - OneHandedWeapon_DoOrDieMonsters
    - TwoHandedWeapon_DoOrDieMonsters
  NoLossOnDeath_DoOrDieMonsters:
    - Equipment_DoOrDieMonsters
  NoTeleportable_DoOrDieMonsters:
    - Metal_DoOrDieMonsters
    - Ore_DoOrDieMonsters

# all:
#   weight factor: 0.7
  
# Weaponkits_DoOrDieMonsters:
#   # those are way to heavy imho
#   weight factor: 0.2

# Stackable_DoOrDieMonsters:
#   stack factor: 2

# NoTeleportable_DoOrDieMonsters:
#   teleportable: no

# NoLossOnDeath_DoOrDieMonsters:
#   loss: no
